import { milestoneAgeStatuses } from "@/db/schema";

export const milestoneIdStatuses: (typeof milestoneAgeStatuses.$inferInsert)[] = [
    {"milestoneId": 1, "month": 0, "achievementRate": "RED"},

    {"milestoneId": 2, "month": 0, "achievementRate": "GREEN"},
    {"milestoneId": 2, "month": 1, "achievementRate": "YELLOW"},
    {"milestoneId": 2, "month": 2, "achievementRate": "RED"},

    {"milestoneId": 3, "month": 0, "achievementRate": "GREEN"},
    {"milestoneId": 3, "month": 1, "achievementRate": "YELLOW"},
    {"milestoneId": 3, "month": 2, "achievementRate": "RED"},

    {"milestoneId": 4, "month": 0, "achievementRate": "YELLOW"},
    {"milestoneId": 4, "month": 1, "achievementRate": "YELLOW"},
    {"milestoneId": 4, "month": 2, "achievementRate": "YELLOW"},
    {"milestoneId": 4, "month": 3, "achievementRate": "ORANGE"},
    {"milestoneId": 4, "month": 4, "achievementRate": "RED"},

    {"milestoneId": 5, "month": 3, "achievementRate": "RED"},

    {"milestoneId": 6, "month": 3, "achievementRate": "RED"},

    {"milestoneId": 7, "month": 3, "achievementRate": "ORANGE"},
    {"milestoneId": 7, "month": 4, "achievementRate": "RED"},

    {"milestoneId": 8, "month": 3, "achievementRate": "YELLOW"},
    {"milestoneId": 8, "month": 4, "achievementRate": "RED"},

    {"milestoneId": 9, "month": 3, "achievementRate": "YELLOW"},
    {"milestoneId": 9, "month": 4, "achievementRate": "RED"},

    {"milestoneId": 10, "month": 3, "achievementRate": "YELLOW"},
    {"milestoneId": 10, "month": 4, "achievementRate": "ORANGE"},
    {"milestoneId": 10, "month": 5, "achievementRate": "RED"},


    {"milestoneId": 11, "month": 6, "achievementRate": "RED"},

    {"milestoneId": 12, "month": 6, "achievementRate": "ORANGE"},
    {"milestoneId": 12, "month": 7, "achievementRate": "ORANGE"},
    {"milestoneId": 12, "month": 8, "achievementRate": "RED"},

    {"milestoneId": 13, "month": 6, "achievementRate": "YELLOW"},
    {"milestoneId": 13, "month": 7, "achievementRate": "YELLOW"},
    {"milestoneId": 13, "month": 8, "achievementRate": "ORANGE"},
    {"milestoneId": 13, "month": 9, "achievementRate": "RED"},

    {"milestoneId": 14, "month": 6, "achievementRate": "YELLOW"},
    {"milestoneId": 14, "month": 7, "achievementRate": "YELLOW"},
    {"milestoneId": 14, "month": 8, "achievementRate": "ORANGE"},
    {"milestoneId": 14, "month": 9, "achievementRate": "RED"},

    {"milestoneId": 15, "month": 6, "achievementRate": "YELLOW"},
    {"milestoneId": 15, "month": 7, "achievementRate": "YELLOW"},
    {"milestoneId": 15, "month": 8, "achievementRate": "ORANGE"},
    {"milestoneId": 15, "month": 9, "achievementRate": "RED"},

    {"milestoneId": 16, "month": 9, "achievementRate": "RED"},

    {"milestoneId": 17, "month": 9, "achievementRate": "RED"},

    {"milestoneId": 18, "month": 9, "achievementRate": "RED"},

    {"milestoneId": 19, "month": 9, "achievementRate": "RED"},

    {"milestoneId": 20, "month": 9, "achievementRate": "ORANGE"},
    {"milestoneId": 20, "month": 10, "achievementRate": "RED"},

    {"milestoneId": 21, "month": 9, "achievementRate": "YELLOW"},
    {"milestoneId": 21, "month": 10, "achievementRate": "ORANGE"},
    {"milestoneId": 21, "month": 11, "achievementRate": "RED"},

    {"milestoneId": 22, "month": 9, "achievementRate": "GREEN"},
    {"milestoneId": 22, "month": 10, "achievementRate": "YELLOW"},
    {"milestoneId": 22, "month": 11, "achievementRate": "ORANGE"},
    {"milestoneId": 22, "month": 12, "achievementRate": "RED"},

    {"milestoneId": 23, "month": 9, "achievementRate": "YELLOW"},
    {"milestoneId": 23, "month": 10, "achievementRate": "YELLOW"},
    {"milestoneId": 23, "month": 11, "achievementRate": "ORANGE"},
    {"milestoneId": 23, "month": 12, "achievementRate": "RED"},

    {"milestoneId": 24, "month": 9, "achievementRate": "GREEN"},
    {"milestoneId": 24, "month": 10, "achievementRate": "YELLOW"},
    {"milestoneId": 24, "month": 11, "achievementRate": "YELLOW"},
    {"milestoneId": 24, "month": 12, "achievementRate": "ORANGE"},
    {"milestoneId": 24, "month": 13, "achievementRate": "ORANGE"},
    {"milestoneId": 24, "month": 14, "achievementRate": "RED"},

    {"milestoneId": 25, "month": 12, "achievementRate": "RED"},

    {"milestoneId": 26, "month": 12, "achievementRate": "RED"},

    {"milestoneId": 27, "month": 12, "achievementRate": "ORANGE"},
    {"milestoneId": 27, "month": 13, "achievementRate": "ORANGE"},
    {"milestoneId": 27, "month": 14, "achievementRate": "RED"},

    {"milestoneId": 28, "month": 12, "achievementRate": "YELLOW"},
    {"milestoneId": 28, "month": 13, "achievementRate": "YELLOW"},
    {"milestoneId": 28, "month": 14, "achievementRate": "ORANGE"},
    {"milestoneId": 28, "month": 15, "achievementRate": "RED"},

    {"milestoneId": 29, "month": 12, "achievementRate": "YELLOW"},
    {"milestoneId": 29, "month": 13, "achievementRate": "YELLOW"},
    {"milestoneId": 29, "month": 14, "achievementRate": "YELLOW"},
    {"milestoneId": 29, "month": 15, "achievementRate": "ORANGE"},
    {"milestoneId": 29, "month": 16, "achievementRate": "ORANGE"},
    {"milestoneId": 29, "month": 17, "achievementRate": "RED"},

    {"milestoneId": 30, "month": 12, "achievementRate": "GREEN"},
    {"milestoneId": 30, "month": 13, "achievementRate": "GREEN"},
    {"milestoneId": 30, "month": 14, "achievementRate": "YELLOW"},
    {"milestoneId": 30, "month": 15, "achievementRate": "YELLOW"},
    {"milestoneId": 30, "month": 16, "achievementRate": "YELLOW"},
    {"milestoneId": 30, "month": 17, "achievementRate": "YELLOW"},
    {"milestoneId": 30, "month": 18, "achievementRate": "ORANGE"},
    {"milestoneId": 30, "month": 19, "achievementRate": "RED"},

    {"milestoneId": 31, "month": 18, "achievementRate": "RED"},

    {"milestoneId": 32, "month": 18, "achievementRate": "RED"},

    {"milestoneId": 33, "month": 18, "achievementRate": "RED"},

    {"milestoneId": 34, "month": 18, "achievementRate": "ORANGE"},
    {"milestoneId": 34, "month": 19, "achievementRate": "ORANGE"},
    {"milestoneId": 34, "month": 20, "achievementRate": "ORANGE"},
    {"milestoneId": 34, "month": 21, "achievementRate": "RED"},

    {"milestoneId": 35, "month": 18, "achievementRate": "YELLOW"},
    {"milestoneId": 35, "month": 19, "achievementRate": "ORANGE"},
    {"milestoneId": 35, "month": 20, "achievementRate": "ORANGE"},
    {"milestoneId": 35, "month": 21, "achievementRate": "ORANGE"},
    {"milestoneId": 35, "month": 22, "achievementRate": "ORANGE"},
    {"milestoneId": 35, "month": 23, "achievementRate": "ORANGE"},
    {"milestoneId": 35, "month": 24, "achievementRate": "RED"},

    {"milestoneId": 36, "month": 18, "achievementRate": "YELLOW"},
    {"milestoneId": 36, "month": 19, "achievementRate": "YELLOW"},
    {"milestoneId": 36, "month": 20, "achievementRate": "YELLOW"},
    {"milestoneId": 36, "month": 21, "achievementRate": "YELLOW"},
    {"milestoneId": 36, "month": 22, "achievementRate": "ORANGE"},
    {"milestoneId": 36, "month": 23, "achievementRate": "ORANGE"},
    {"milestoneId": 36, "month": 24, "achievementRate": "ORANGE"},
    {"milestoneId": 36, "month": 25, "achievementRate": "ORANGE"},
    {"milestoneId": 36, "month": 26, "achievementRate": "RED"},

    {"milestoneId": 37, "month": 18, "achievementRate": "GREEN"},
    {"milestoneId": 37, "month": 19, "achievementRate": "GREEN"},
    {"milestoneId": 37, "month": 20, "achievementRate": "GREEN"},
    {"milestoneId": 37, "month": 21, "achievementRate": "GREEN"},
    {"milestoneId": 37, "month": 22, "achievementRate": "YELLOW"},
    {"milestoneId": 37, "month": 23, "achievementRate": "YELLOW"},
    {"milestoneId": 37, "month": 24, "achievementRate": "YELLOW"},
    {"milestoneId": 37, "month": 25, "achievementRate": "YELLOW"},
    {"milestoneId": 37, "month": 26, "achievementRate": "YELLOW"},
    {"milestoneId": 37, "month": 27, "achievementRate": "ORANGE"},
    {"milestoneId": 37, "month": 28, "achievementRate": "ORANGE"},
    {"milestoneId": 37, "month": 29, "achievementRate": "ORANGE"},
    {"milestoneId": 37, "month": 30, "achievementRate": "ORANGE"},
    {"milestoneId": 37, "month": 31, "achievementRate": "RED"},

    {"milestoneId": 38, "month": 24, "achievementRate": "RED"},

    {"milestoneId": 39, "month": 24, "achievementRate": "RED"},

    {"milestoneId": 40, "month": 24, "achievementRate": "YELLOW"},
    {"milestoneId": 40, "month": 25, "achievementRate": "YELLOW"},
    {"milestoneId": 40, "month": 26, "achievementRate": "ORANGE"},
    {"milestoneId": 40, "month": 27, "achievementRate": "ORANGE"},
    {"milestoneId": 40, "month": 28, "achievementRate": "ORANGE"},
    {"milestoneId": 40, "month": 29, "achievementRate": "ORANGE"},
    {"milestoneId": 40, "month": 30, "achievementRate": "ORANGE"},
    {"milestoneId": 40, "month": 31, "achievementRate": "RED"},

    {"milestoneId": 41, "month": 24, "achievementRate": "YELLOW"},
    {"milestoneId": 41, "month": 25, "achievementRate": "YELLOW"},
    {"milestoneId": 41, "month": 26, "achievementRate": "YELLOW"},
    {"milestoneId": 41, "month": 27, "achievementRate": "YELLOW"},
    {"milestoneId": 41, "month": 28, "achievementRate": "ORANGE"},
    {"milestoneId": 41, "month": 29, "achievementRate": "ORANGE"},
    {"milestoneId": 41, "month": 30, "achievementRate": "ORANGE"},
    {"milestoneId": 41, "month": 31, "achievementRate": "ORANGE"},
    {"milestoneId": 41, "month": 32, "achievementRate": "RED"},

    {"milestoneId": 42, "month": 24, "achievementRate": "YELLOW"},
    {"milestoneId": 42, "month": 25, "achievementRate": "YELLOW"},
    {"milestoneId": 42, "month": 26, "achievementRate": "YELLOW"},
    {"milestoneId": 42, "month": 27, "achievementRate": "YELLOW"},
    {"milestoneId": 42, "month": 28, "achievementRate": "ORANGE"},
    {"milestoneId": 42, "month": 29, "achievementRate": "ORANGE"},
    {"milestoneId": 42, "month": 30, "achievementRate": "ORANGE"},
    {"milestoneId": 42, "month": 31, "achievementRate": "ORANGE"},
    {"milestoneId": 42, "month": 32, "achievementRate": "RED"},

    {"milestoneId": 43, "month": 24, "achievementRate": "YELLOW"},
    {"milestoneId": 43, "month": 25, "achievementRate": "YELLOW"},
    {"milestoneId": 43, "month": 26, "achievementRate": "YELLOW"},
    {"milestoneId": 43, "month": 27, "achievementRate": "ORANGE"},
    {"milestoneId": 43, "month": 28, "achievementRate": "ORANGE"},
    {"milestoneId": 43, "month": 29, "achievementRate": "ORANGE"},
    {"milestoneId": 43, "month": 30, "achievementRate": "ORANGE"},
    {"milestoneId": 43, "month": 31, "achievementRate": "ORANGE"},
    {"milestoneId": 43, "month": 32, "achievementRate": "ORANGE"},
    {"milestoneId": 43, "month": 33, "achievementRate": "ORANGE"},
    {"milestoneId": 43, "month": 34, "achievementRate": "ORANGE"},

    {"milestoneId": 44, "month": 24, "achievementRate": "GREEN"},
    {"milestoneId": 44, "month": 25, "achievementRate": "GREEN"},
    {"milestoneId": 44, "month": 26, "achievementRate": "GREEN"},
    {"milestoneId": 44, "month": 27, "achievementRate": "YELLOW"},
    {"milestoneId": 44, "month": 28, "achievementRate": "YELLOW"},
    {"milestoneId": 44, "month": 29, "achievementRate": "YELLOW"},
    {"milestoneId": 44, "month": 30, "achievementRate": "YELLOW"},
    {"milestoneId": 44, "month": 31, "achievementRate": "YELLOW"},
    {"milestoneId": 44, "month": 32, "achievementRate": "ORANGE"},
    {"milestoneId": 44, "month": 33, "achievementRate": "ORANGE"},
    {"milestoneId": 44, "month": 34, "achievementRate": "ORANGE"},

    {"milestoneId": 45, "month": 36, "achievementRate": "RED"},
    {"milestoneId": 45, "month": 37, "achievementRate": "RED"},


    {"milestoneId": 46, "month": 36, "achievementRate": "ORANGE"},
    {"milestoneId": 46, "month": 37, "achievementRate": "ORANGE"},
    {"milestoneId": 46, "month": 38, "achievementRate": "RED"},
    {"milestoneId": 46, "month": 39, "achievementRate": "RED"},

    {"milestoneId": 47, "month": 36, "achievementRate": "YELLOW"},
    {"milestoneId": 47, "month": 37, "achievementRate": "YELLOW"},
    {"milestoneId": 47, "month": 38, "achievementRate": "YELLOW"},
    {"milestoneId": 47, "month": 39, "achievementRate": "YELLOW"},
    {"milestoneId": 47, "month": 40, "achievementRate": "ORANGE"},
    {"milestoneId": 47, "month": 41, "achievementRate": "ORANGE"},
    {"milestoneId": 47, "month": 42, "achievementRate": "ORANGE"},
    {"milestoneId": 47, "month": 43, "achievementRate": "ORANGE"},
    {"milestoneId": 47, "month": 44, "achievementRate": "RED"},
    {"milestoneId": 47, "month": 45, "achievementRate": "RED"},

    {"milestoneId": 48, "month": 36, "achievementRate": "ORANGE"},
    {"milestoneId": 48, "month": 37, "achievementRate": "ORANGE"},
    {"milestoneId": 48, "month": 38, "achievementRate": "ORANGE"},
    {"milestoneId": 48, "month": 39, "achievementRate": "ORANGE"},
    {"milestoneId": 48, "month": 40, "achievementRate": "ORANGE"},
    {"milestoneId": 48, "month": 41, "achievementRate": "ORANGE"},
    {"milestoneId": 48, "month": 42, "achievementRate": "RED"},
    {"milestoneId": 48, "month": 43, "achievementRate": "RED"},

    {"milestoneId": 49, "month": 36, "achievementRate": "YELLOW"},
    {"milestoneId": 49, "month": 37, "achievementRate": "YELLOW"},
    {"milestoneId": 49, "month": 38, "achievementRate": "YELLOW"},
    {"milestoneId": 49, "month": 39, "achievementRate": "YELLOW"},
    {"milestoneId": 49, "month": 40, "achievementRate": "ORANGE"},
    {"milestoneId": 49, "month": 41, "achievementRate": "ORANGE"},
    {"milestoneId": 49, "month": 42, "achievementRate": "ORANGE"},
    {"milestoneId": 49, "month": 43, "achievementRate": "ORANGE"},
    {"milestoneId": 49, "month": 44, "achievementRate": "ORANGE"},
    {"milestoneId": 49, "month": 45, "achievementRate": "ORANGE"},
    {"milestoneId": 49, "month": 46, "achievementRate": "RED"},
    {"milestoneId": 49, "month": 47, "achievementRate": "RED"},

    {"milestoneId": 50, "month": 36, "achievementRate": "ORANGE"},
    {"milestoneId": 50, "month": 37, "achievementRate": "ORANGE"},
    {"milestoneId": 50, "month": 38, "achievementRate": "ORANGE"},
    {"milestoneId": 50, "month": 39, "achievementRate": "ORANGE"},
    {"milestoneId": 50, "month": 40, "achievementRate": "ORANGE"},
    {"milestoneId": 50, "month": 41, "achievementRate": "ORANGE"},
    {"milestoneId": 50, "month": 42, "achievementRate": "ORANGE"},
    {"milestoneId": 50, "month": 43, "achievementRate": "ORANGE"},
    {"milestoneId": 50, "month": 44, "achievementRate": "RED"},
    {"milestoneId": 50, "month": 45, "achievementRate": "RED"},

    {"milestoneId": 51, "month": 36, "achievementRate": "YELLOW"},
    {"milestoneId": 51, "month": 37, "achievementRate": "YELLOW"},
    {"milestoneId": 51, "month": 38, "achievementRate": "YELLOW"},
    {"milestoneId": 51, "month": 39, "achievementRate": "YELLOW"},
    {"milestoneId": 51, "month": 40, "achievementRate": "ORANGE"},
    {"milestoneId": 51, "month": 41, "achievementRate": "ORANGE"},
    {"milestoneId": 51, "month": 42, "achievementRate": "ORANGE"},
    {"milestoneId": 51, "month": 43, "achievementRate": "ORANGE"},
    {"milestoneId": 51, "month": 44, "achievementRate": "ORANGE"},
    {"milestoneId": 51, "month": 45, "achievementRate": "ORANGE"},
    {"milestoneId": 51, "month": 46, "achievementRate": "ORANGE"},
    {"milestoneId": 51, "month": 47, "achievementRate": "ORANGE"},

    {"milestoneId": 52, "month": 48, "achievementRate": "RED"},
    {"milestoneId": 52, "month": 49, "achievementRate": "RED"},

    {"milestoneId": 53, "month": 48, "achievementRate": "RED"},
    {"milestoneId": 53, "month": 49, "achievementRate": "RED"},

    {"milestoneId": 54, "month": 48, "achievementRate": "YELLOW"},
    {"milestoneId": 54, "month": 49, "achievementRate": "YELLOW"},
    {"milestoneId": 54, "month": 50, "achievementRate": "ORANGE"},
    {"milestoneId": 54, "month": 51, "achievementRate": "ORANGE"},
    {"milestoneId": 54, "month": 52, "achievementRate": "ORANGE"},
    {"milestoneId": 54, "month": 53, "achievementRate": "ORANGE"},
    {"milestoneId": 54, "month": 54, "achievementRate": "ORANGE"},
    {"milestoneId": 54, "month": 55, "achievementRate": "ORANGE"},
    {"milestoneId": 54, "month": 56, "achievementRate": "RED"},
    {"milestoneId": 54, "month": 57, "achievementRate": "RED"},

    {"milestoneId": 55, "month": 48, "achievementRate": "ORANGE"},
    {"milestoneId": 55, "month": 49, "achievementRate": "ORANGE"},
    {"milestoneId": 55, "month": 50, "achievementRate": "ORANGE"},
    {"milestoneId": 55, "month": 51, "achievementRate": "ORANGE"},
    {"milestoneId": 55, "month": 52, "achievementRate": "ORANGE"},
    {"milestoneId": 55, "month": 53, "achievementRate": "ORANGE"},
    {"milestoneId": 55, "month": 54, "achievementRate": "ORANGE"},
    {"milestoneId": 55, "month": 55, "achievementRate": "ORANGE"},
    {"milestoneId": 55, "month": 56, "achievementRate": "RED"},
    {"milestoneId": 55, "month": 57, "achievementRate": "RED"},

    {"milestoneId": 56, "month": 48, "achievementRate": "YELLOW"},
    {"milestoneId": 56, "month": 49, "achievementRate": "YELLOW"},
    {"milestoneId": 56, "month": 50, "achievementRate": "YELLOW"},
    {"milestoneId": 56, "month": 51, "achievementRate": "YELLOW"},
    {"milestoneId": 56, "month": 52, "achievementRate": "ORANGE"},
    {"milestoneId": 56, "month": 53, "achievementRate": "ORANGE"},
    {"milestoneId": 56, "month": 54, "achievementRate": "ORANGE"},
    {"milestoneId": 56, "month": 55, "achievementRate": "ORANGE"},
    {"milestoneId": 56, "month": 56, "achievementRate": "ORANGE"},
    {"milestoneId": 56, "month": 57, "achievementRate": "ORANGE"},
    {"milestoneId": 56, "month": 58, "achievementRate": "RED"},
    {"milestoneId": 56, "month": 59, "achievementRate": "RED"},

    {"milestoneId": 57, "month": 48, "achievementRate": "YELLOW"},
    {"milestoneId": 57, "month": 49, "achievementRate": "YELLOW"},
    {"milestoneId": 57, "month": 50, "achievementRate": "YELLOW"},
    {"milestoneId": 57, "month": 51, "achievementRate": "YELLOW"},
    {"milestoneId": 57, "month": 52, "achievementRate": "YELLOW"},
    {"milestoneId": 57, "month": 53, "achievementRate": "YELLOW"},
    {"milestoneId": 57, "month": 54, "achievementRate": "YELLOW"},
    {"milestoneId": 57, "month": 55, "achievementRate": "YELLOW"},
    {"milestoneId": 57, "month": 56, "achievementRate": "ORANGE"},
    {"milestoneId": 57, "month": 57, "achievementRate": "ORANGE"},
    {"milestoneId": 57, "month": 58, "achievementRate": "RED"},
    {"milestoneId": 57, "month": 59, "achievementRate": "RED"},

    {"milestoneId": 58, "month": 48, "achievementRate": "GREEN"},
    {"milestoneId": 58, "month": 49, "achievementRate": "GREEN"},
    {"milestoneId": 58, "month": 50, "achievementRate": "GREEN"},
    {"milestoneId": 58, "month": 51, "achievementRate": "GREEN"},
    {"milestoneId": 58, "month": 52, "achievementRate": "YELLOW"},
    {"milestoneId": 58, "month": 53, "achievementRate": "YELLOW"},
    {"milestoneId": 58, "month": 54, "achievementRate": "YELLOW"},
    {"milestoneId": 58, "month": 55, "achievementRate": "YELLOW"},
    {"milestoneId": 58, "month": 56, "achievementRate": "YELLOW"},
    {"milestoneId": 58, "month": 57, "achievementRate": "YELLOW"},
    {"milestoneId": 58, "month": 58, "achievementRate": "ORANGE"},
    {"milestoneId": 58, "month": 59, "achievementRate": "ORANGE"},
    {"milestoneId": 58, "month": 60, "achievementRate": "RED"},
    {"milestoneId": 58, "month": 61, "achievementRate": "RED"},

    {"milestoneId": 59, "month": 48, "achievementRate": "GREEN"},
    {"milestoneId": 59, "month": 49, "achievementRate": "GREEN"},
    {"milestoneId": 59, "month": 50, "achievementRate": "YELLOW"},
    {"milestoneId": 59, "month": 51, "achievementRate": "YELLOW"},
    {"milestoneId": 59, "month": 52, "achievementRate": "YELLOW"},
    {"milestoneId": 59, "month": 53, "achievementRate": "YELLOW"},
    {"milestoneId": 59, "month": 54, "achievementRate": "YELLOW"},
    {"milestoneId": 59, "month": 55, "achievementRate": "YELLOW"},
    {"milestoneId": 59, "month": 56, "achievementRate": "YELLOW"},
    {"milestoneId": 59, "month": 57, "achievementRate": "YELLOW"},
    {"milestoneId": 59, "month": 58, "achievementRate": "ORANGE"},
    {"milestoneId": 59, "month": 59, "achievementRate": "ORANGE"},
    {"milestoneId": 59, "month": 60, "achievementRate": "ORANGE"},
    {"milestoneId": 59, "month": 61, "achievementRate": "ORANGE"},
    {"milestoneId": 59, "month": 62, "achievementRate": "RED"},
    {"milestoneId": 59, "month": 63, "achievementRate": "RED"},

  ]
  